### ISSUE TITLE
Issues when adding to nuxt project

### ISSUE THREAD

**Issue by jd1378** [lucaspulliese/vue-cool-lightbox#8] opened 2020-02-12 22:08 UTC
Hi,
I don't know why this happen , but when i add this package to my nuxt project and go to dev mode it starts showing errors about core-js , [here is the gist showing the error](https://gist.github.com/jd1378/27b0eb726eb370f8fcece336b0b3fad5)
can you guess why it happens ?
I did test this several times by adding and removing it to the same project only and this package made it happen.
thanks

**Comment by lucaspulliese** [comment] 2020-02-12 22:21
Hi @jd1378!

Could you copy & paste here your package.json? I want to reproduce it locally.

**Comment by jd1378** [comment] 2020-02-12 22:24
```{
  "name": "fpitems-front",
  "version": "1.0.0",
  "description": "Fronted developement of fpitem project",
  "author": "Javad Mnjd",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "devcross": "cross-env NODE_ENV=development HOST=0.0.0.0 PORT=3000 nuxt",
    "dev-debug": "cross-env NODE_ENV=development HOST=0.0.0.0 PORT=3000 node --inspect-brk=9229 node_modules/nuxt/bin/nuxt.js",
    "build": "nuxt build",
    "build-standalone": "nuxt build --standalone",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore ."
  },
  "dependencies": {
    "@hyjiacan/vue-slideout": "^2.3.1",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/component-cache": "^1.1.5",
    "@nuxtjs/pwa": "^3.0.0-0",
    "@nuxtjs/sitemap": "^2.0.1",
    "@nuxtjs/toast": "^3.3.0",
    "axios": "^0.19.0",
    "bootstrap": "^4.4.0",
    "bootstrap-vue": "^2.1.0",
    "cookie-universal-nuxt": "^2.0.19",
    "font-awesome": "^4.7.0",
    "hooper": "^0.3.4",
    "lodash": "^4.17.15",
    "node-sass": "^4.13.0",
    "nuxt": "^2.0.0",
    "nuxt-i18n": "^6.4.1",
    "nuxt-start": "^2.10.2",
    "sass-loader": "^8.0.0",
    "sitemap": "^5.1.0",
    "v-click-outside": "^3.0.0",
    "v-lazy-image": "^1.3.2",
    "vee-validate": "^3.1.1",
    "vue-awesome-swiper": "^3.1.3",
    "vue-cool-lightbox": "^1.0.5",
    "vue-js-toggle-button": "^1.3.3",
    "vue-lazyload": "^1.3.3",
    "vue-persian-datetime-picker": "^2.1.2",
    "vue-select": "^3.4.0",
    "vue-slider-component": "^3.0.43",
    "vue-snotify": "^3.2.1",
    "vue-sweetalert2": "^3.0.0",
    "vue-the-mask": "^0.11.1",
    "vuex-persistedstate": "^2.7.0",
    "vuex-shared-mutations": "^1.0.2"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^1.0.1",
    "@nuxtjs/eslint-module": "^1.0.0",
    "@nuxtjs/google-analytics": "^2.2.1",
    "@nuxtjs/proxy": "^1.3.3",
    "babel-eslint": "^10.0.1",
    "eslint": "^6.7.1",
    "eslint-config-prettier": "^4.1.0",
    "eslint-plugin-nuxt": "^0.5.0",
    "eslint-plugin-prettier": "^3.0.1",
    "prettier": "^1.19.1"
  }
}
```

**Comment by jd1378** [comment] 2020-02-12 22:27
Please let me know when you have copied it , I don't want this information to stay on the internet ;)

**Comment by lucaspulliese** [comment] 2020-02-12 22:33
Done! You can remove it.

I'm gonna try to fix this issue tomorrow.

**Comment by lucaspulliese** [comment] 2020-02-12 23:06
I fixed it doing:

`npm i -D core-js@2 @babel/runtime-corejs2`

https://nuxtjs.org/guide/release-notes/#v2.6.0

I guess you have installed core-js: ^3.3.2, and I guess because vue-cool-lightbox has it as a dependency (which shouldn't be).

Let me know if it works for you!

**Comment by jd1378** [comment] 2020-02-13 09:51
Ah, I see , I had seen that there's some issues around core-js in nuxt github
I'll try to install version 2 and try again in few days (sorry that i can't do sooner).
thanks for looking into it

**Comment by jd1378** [comment] 2020-02-13 23:05
Hi @lucaspulliese 
I had time today to try it
I can confirm the issues with core-js are gone
but currently your component is still unusable in nuxt ssr because of using document object
I'm getting error in `node_modules\vue-cool-lightbox\dist\vue-cool-lightbox.umd.js` at line ` var HEAD = document.head || document.getElementsByTagName('head')[0];`

**Comment by lucaspulliese** [comment] 2020-02-14 00:07
I know, at the moment you can use it adding it in nuxt.config.js as a plugin with ssr: false

```javascript
plugins: [
    { src: '~/plugins/cool-lightbox', ssr: false },
 ]
```

And in cool-lightbox.js inside plugins folder: 

```javascript
import Vue from 'vue'
import CoolLightBox from 'vue-cool-lightbox'
Vue.use(CoolLightBox)
```

I will be working to use it during SSR, thanks @ jd1378

**Comment by jd1378** [comment] 2020-02-14 10:01
I think the problem with that approach is that it's gonna load everywhere even where I don't need it i.e. index (If I'm right, because I'm not sure about this)

**Comment by lucaspulliese** [comment] 2020-02-15 20:42
Added SSR in version 1.0.11. 

Tell me if everything is ok so  I can close the issue.

**Comment by jd1378** [comment] 2020-02-16 15:35
I could use it without any problem. Great job 👍

**Closed** 2020-02-16 15:39 UTC
Labels: enhancement

**Comment by pankajadhyapak** [comment] 2020-03-14 16:42
I'm having the same issue not able to use in `nuxtjs project` works fine in development mode, but when I build the project it's not working, anyone faced the same issue?
